import type { Analysis } from "./types";
import { formatDistance, formatDuration, formatPace } from "./utils";

// Build a human-readable Markdown report from an analysis (coach report + stats
// + per-leg breakdown), suitable for downloading/printing/sharing.
export function buildReportMarkdown(analysis: Analysis, raceName = "Race"): string {
  const m = analysis.metrics;
  const s = analysis.scores;
  const c = analysis.coach;
  const date = analysis.created_at
    ? new Date(analysis.created_at).toLocaleString()
    : "";
  const L: string[] = [];
  L.push(`# RouteForge — ${raceName}`);
  if (date) L.push(`_${date}_`);
  L.push("");

  L.push("## Overview");
  L.push(
    `- **Distance:** ${formatDistance(m.distance_m)}`,
    `- **Time:** ${formatDuration(m.duration_s)}`,
    `- **Avg pace:** ${formatPace(m.avg_pace_min_km)}`,
    `- **Climb:** ${Math.round(m.total_climb_m)} m`,
    `- **Controls:** ${analysis.controls.length}`,
    `- **Mistakes:** ${analysis.mistakes.length}`,
    ""
  );

  L.push("## Performance scores (0–100)");
  L.push(
    `- Overall: **${s.overall}**`,
    `- Navigation: ${s.navigation}`,
    `- Fitness: ${s.fitness}`,
    `- Execution: ${s.execution}`,
    `- Route choice: ${s.route_choice}`,
    ""
  );

  L.push(`## AI Coach report${c.generated_by ? ` _(${c.generated_by})_` : ""}`);
  if (c.overview || c.summary) L.push(c.overview || c.summary, "");
  const section = (title: string, items?: string[]) => {
    if (items && items.length) {
      L.push(`### ${title}`);
      items.forEach((it) => L.push(`- ${it}`));
      L.push("");
    }
  };
  if (c.focus_areas?.length) L.push(`**Focus areas:** ${c.focus_areas.join(", ")}`, "");
  section("Strengths", c.strengths);
  section("Weaknesses", c.weaknesses);
  section("Key mistakes", c.mistakes);
  section("Advice", c.advice);
  section("Training plan", c.training);

  if (analysis.legs.length) {
    L.push("## Leg-by-leg");
    L.push("| Leg | From→To | Time | Loss | Rank |");
    L.push("|---|---|---|---|---|");
    analysis.legs.forEach((leg) => {
      L.push(
        `| ${leg.number} | ${leg.from_control}→${leg.to_control} | ` +
          `${leg.time_s != null ? formatDuration(leg.time_s) : "–"} | ` +
          `${leg.time_loss_s ? "+" + formatDuration(leg.time_loss_s) : "–"} | ` +
          `${leg.rank ?? "–"} |`
      );
    });
    L.push("");
  }

  L.push("---", "_Generated by RouteForge._");
  return L.join("\n");
}

export function downloadReport(analysis: Analysis, raceName = "Race"): void {
  if (typeof window === "undefined") return;
  const md = buildReportMarkdown(analysis, raceName);
  const safe = raceName.replace(/[^\w-]+/g, "_").slice(0, 50) || "race";
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `routeforge-${safe}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
