import type { Analysis } from "./types";
import { formatDistance, formatDuration, formatPace } from "./utils";

// Build a human-readable Markdown report from an analysis (coach report + stats
// + per-leg breakdown), suitable for downloading/printing/sharing.
export function buildReportMarkdown(analysis: Analysis, raceName = "Race"): string {
  const m = analysis.metrics;
  const s = analysis.scores;
  const c = analysis.coach;
  const date = analysis.created_at
    ? new Date(analysis.created_at).toLocaleString()
    : "";
  const L: string[] = [];
  L.push(`# RouteForge — ${raceName}`);
  if (date) L.push(`_${date}_`);
  L.push("");

  L.push("## Overview");
  L.push(
    `- **Distance:** ${formatDistance(m.distance_m)}`,
    `- **Time:** ${formatDuration(m.duration_s)}`,
    `- **Avg pace:** ${formatPace(m.avg_pace_min_km)}`,
    `- **Climb:** ${Math.round(m.total_climb_m)} m`,
    `- **Controls:** ${analysis.controls.length}`,
    `- **Mistakes:** ${analysis.mistakes.length}`,
    ""
  );

  L.push("## Performance scores (0–100)");
  L.push(
    `- Overall: **${s.overall}**`,
    `- Navigation: ${s.navigation}`,
    `- Fitness: ${s.fitness}`,
    `- Execution: ${s.execution}`,
    `- Route choice: ${s.route_choice}`,
    ""
  );

  L.push(`## AI Coach report${c.generated_by ? ` _(${c.generated_by})_` : ""}`);
  if (c.overview || c.summary) L.push(c.overview || c.summary, "");
  const section = (title: string, items?: string[]) => {
    if (items && items.length) {
      L.push(`### ${title}`);
      items.forEach((it) => L.push(`- ${it}`));
      L.push("");
    }
  };
  if (c.focus_areas?.length) L.push(`**Focus areas:** ${c.focus_areas.join(", ")}`, "");
  section("Strengths", c.strengths);
  section("Weaknesses", c.weaknesses);
  section("Key mistakes", c.mistakes);
  section("Advice", c.advice);
  section("Training plan", c.training);

  if (analysis.legs.length) {
    L.push("## Leg-by-leg");
    L.push("| Leg | From→To | Time | Loss | Rank |");
    L.push("|---|---|---|---|---|");
    analysis.legs.forEach((leg) => {
      L.push(
        `| ${leg.number} | ${leg.from_control}→${leg.to_control} | ` +
          `${leg.time_s != null ? formatDuration(leg.time_s) : "–"} | ` +
          `${leg.time_loss_s ? "+" + formatDuration(leg.time_loss_s) : "–"} | ` +
          `${leg.rank ?? "–"} |`
      );
    });
    L.push("");
  }

  L.push("---", "_Generated by RouteForge._");
  return L.join("\n");
}

// One-click PDF of the same report (multi-page, text-based).
export async function downloadReportPdf(
  analysis: Analysis,
  raceName = "Race"
): Promise<void> {
  if (typeof window === "undefined") return;
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 42;
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensure = (h: number) => {
    if (y + h > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };
  const heading = (text: string, size = 13) => {
    ensure(size + 18);
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.setTextColor(25, 110, 60);
    doc.text(text, margin, y);
    y += size + 4;
  };
  const para = (text: string, size = 10, color = 60) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(color);
    for (const line of doc.splitTextToSize(text, maxW) as string[]) {
      ensure(size + 4);
      doc.text(line, margin, y);
      y += size + 4;
    }
  };
  const bullets = (items: string[], size = 10) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(60);
    for (const it of items) {
      const lines = doc.splitTextToSize(it, maxW - 14) as string[];
      lines.forEach((line, i) => {
        ensure(size + 4);
        doc.text((i === 0 ? "•  " : "    ") + line, margin, y);
        y += size + 4;
      });
    }
  };

  const m = analysis.metrics;
  const s = analysis.scores;
  const c = analysis.coach;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(20);
  doc.text(`RouteForge — ${raceName}`, margin, y);
  y += 22;
  if (analysis.created_at) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(new Date(analysis.created_at).toLocaleString(), margin, y);
    y += 14;
  }

  heading("Overview");
  para(
    `Distance ${formatDistance(m.distance_m)}    Time ${formatDuration(m.duration_s)}    ` +
      `Avg pace ${formatPace(m.avg_pace_min_km)}    Climb ${Math.round(m.total_climb_m)} m    ` +
      `Controls ${analysis.controls.length}    Mistakes ${analysis.mistakes.length}`
  );

  heading("Performance scores (0-100)");
  para(
    `Overall ${s.overall}    Navigation ${s.navigation}    Fitness ${s.fitness}    ` +
      `Execution ${s.execution}    Route choice ${s.route_choice}`
  );

  heading(`AI Coach report${c.generated_by ? `  (${c.generated_by})` : ""}`);
  if (c.overview || c.summary) para(c.overview || c.summary);
  if (c.focus_areas?.length) para(`Focus areas: ${c.focus_areas.join(", ")}`, 10, 110);
  const sec = (t: string, items?: string[]) => {
    if (items && items.length) {
      heading(t, 12);
      bullets(items);
    }
  };
  sec("Strengths", c.strengths);
  sec("Weaknesses", c.weaknesses);
  sec("Key mistakes", c.mistakes);
  sec("Advice", c.advice);
  sec("Training plan", c.training);

  if (analysis.legs.length) {
    heading("Leg-by-leg");
    para("Leg    From->To    Time    Loss    Rank", 9, 110);
    analysis.legs.forEach((leg) =>
      para(
        `${leg.number}    ${leg.from_control}->${leg.to_control}    ` +
          `${leg.time_s != null ? formatDuration(leg.time_s) : "-"}    ` +
          `${leg.time_loss_s ? "+" + formatDuration(leg.time_loss_s) : "-"}    ` +
          `${leg.rank ?? "-"}`,
        9,
        80
      )
    );
  }

  y += 12;
  para("Generated by RouteForge.", 9, 150);
  const safe = raceName.replace(/[^\w-]+/g, "_").slice(0, 50) || "race";
  doc.save(`routeforge-${safe}.pdf`);
}

export function downloadReport(analysis: Analysis, raceName = "Race"): void {
  if (typeof window === "undefined") return;
  const md = buildReportMarkdown(analysis, raceName);
  const safe = raceName.replace(/[^\w-]+/g, "_").slice(0, 50) || "race";
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `routeforge-${safe}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
